- roles/common/tasks/main.yml
- roles/scripts/files/plex_autoscan_url.sh
- roles/scripts/tasks/main.yml
- roles/scripts/templates/plex_autoscan_url.sh.js2
- settings.yml
* A quick way to get the Plex Autoscan URL.
```
$ ./plex_autoscan_url.sh
http://ip:port/key
```
* Updated rclone version to 1.38 in settings.yml
> Plex Autoscan URL script and rclone version edit

- README.md
- roles/motd/tasks/main.yml
update-notifier added unnecessary files. update-notifier-common replaces that
Tested and working.
> Tweak motd

- roles/plex_autoscan/templates/config.json.js2
- roles/scripts/files/plex_autoscan_url.sh
- Fixes json errors that causes plex_autoscan to fail during startup.
- Made plex_autoscan_url script leaner.
> Plex Autoscan config template fix and URL script tweak

- roles/backup/tasks/main.yml
- settings.yml
- Added option for Pushover alerts during backup (to disable leave related variables in settings.yml blank). 
- Moved backup.lock check to the top
> Pushover alerts during backup

- roles/backup/tasks/main.yml
- Added archive file size to pushover msg in backup role.
- Gave pushover tasks names.
> Backup task: added archive file size to pushover msg

- roles/backup/tasks/main.yml
- Updated wording on Pushover messages
- added duration time to final pushover message
>  Backup Task: Tweaks

- roles/backup/tasks/main.yml
- roles/nzbget/tasks/main.yml
- roles/plex_autoscan/templates/config.json.js2
- roles/radarr/tasks/main.yml
- roles/rutorrent/tasks/main.yml
- roles/sonarr/tasks/main.yml
- Backup Task: Wording tweaked 
- Docker: Moved hardlink path out of unionfs
> Docker: Moved hardlink path out of unionfs 

- roles/common/tasks/main.yml
- roles/scripts/files/restart_containers.sh
- roles/scripts/tasks/main.yml
- Added script to start running containers and start them back up.
>  Scripts: Added restart_containers.sh

- cloudbox.yml
- roles/nextcloud/tasks/main.yml
- roles/nginx-proxy/files/proxy.conf
can be installed with install-nextcloud or update-nextcloud
> added nextcloud container

- roles/plex/tasks/main.yml
Changelog: https://github.com/ukdtom/WebTools.bundle/wiki/ChangeLog#v300
>  Webtools: Updated to 3.0.0 

- CHANGELOG.md
- cloudbox.yml
- roles/emby/tasks/main.yml
- To install, run the Cloudbox install command with `--tags install-emby`.
> Added Emby

- roles/emby/tasks/main.yml
For android clients that don't support HTTPS/SSL.
> Emby: added http no-redirect

- README.md
- roles/emby/tasks/main.yml
- roles/plexdrive/templates/plexdrive.service.js2
Doesnt change anything as 10M is the default; Just makes that setting obvious for tweakers.
> Plexdrive: Added default chunk size string

- roles/docker/tasks/main.yml
- Should prevent issues mentioned [here](https://github.com/moby/moby/issues/35933) from happening.
- Will update the version to the latest once a stable release is out.
> Docker: Specified Docker version to 17.09.0

- CHANGELOG.md
- CONTRIBUTING.md
- CREDITS.md
- README.md
> README.md: Updates

- roles/backup/tasks/main.yml
> Backup: include settings.yml and rclone.conf into backup

- roles/common/tasks/main.yml
- roles/plex/tasks/main.yml
- Set Plex hosts: `mf.svc.nhl.com` and `mlb-ws-mf.media.mlb.com` to Lazyman IP. 
- Added: dnspython module
> Added: Lazyman hosts to Plex

- roles/common/tasks/main.yml
- roles/docker/tasks/main.yml
- Added `update-ctop`, `update-ngrok`, and `update-hostess` tags.
- Tweaked docker-ce hold / unhold commands. 
- Updated hostess from 0.2.0 to 0.3.0.
> CB: Misc tweaks

- cloudbox.yml
- roles/plex_patrol/tasks/main.yml
- roles/plex_patrol/templates/settings.ini.js2
> add plex_patrol

- roles/unionfs/tasks/service.yml
- roles/unionfs/templates/mergerfs.service.js2
- roles/unionfs/templates/unionfs.service.js2
This has helped with iowaits for some users
> Closer to what .mount offered

- roles/system/tasks/systctl.yml
This should be plenty for most users.
> Set max_user_watches for plex inotify

- roles/radarr/tasks/main.yml
- roles/sonarr/tasks/main.yml
Modified Sonarr & Radarr tags to check if sickbeard_mp4_automator is enabled and if so then enable iGPU passthrough  (Where supported).
> Passthrough iGPU

- cloudbox.yml
- roles/aliases/tasks/main.yml
Aliases repo can be contributed to at https://github.com/Cloudbox/aliases
> Aliases: Add aliases role to make use of the Cloudbox aliases repo.

- roles/shell/tasks/zsh.yml
As per: https://stackoverflow.com/a/25876379
> Fix description and add line earlier in .zshrc

- roles/rutorrent/defaults/main.yml
Changed rutorrent path to torrents instead of nzbs.
> Fixed rutorrent path.

- roles/netdata/defaults/main.yml
Change to official netdata/netdata image.
> Netdata: Update Docker image

- roles/netdata/defaults/main.yml
> Revert "Netdata: Update Docker image"

- roles/plex/defaults/main.yml
https://github.com/nomego/Lazyman.bundle/commit/82f65782f025187e168524e88aacd1864844ef21
> Plex: Update lookup for LazyMan

- cloudbox.yml
- resources/tasks/docker/create_docker_container.yml
- roles/transfer/defaults/main.yml
- roles/transfer/files/nginx-proxy.vhostd
- roles/transfer/tasks/main.yml
This role will setup the transfer.sh instance to only allow authorized uploads (basic auth).
`transfer_web_user` and `transfer_web_pass` variables can be overridden in `host_vars/localhost.yml`
> Transfer: Host a local version of transfer.sh

- roles/watchtower/tasks/main.yml
This pull request updates the main.yml file to use a different Watchtower container. The previous one was deprecated and over 2 years old. The new container is the actively developed one.
> Updated Watchtower container

- roles/nzbhydra2/defaults/main.yml
Appveyor seems to have problems fetching latest for whatever reason.
> NZBHydra2: Update image.

- defaults/adv_settings.yml.default
- roles/organizr/tasks/main.yml
Backported from develop branch
> Organizr: Update for new upstream image

- roles/backup/files/backup_excludes_list.txt
- roles/jackett/tasks/main.yml
- roles/lidarr/defaults/main.yml
- roles/lidarr/tasks/main.yml
- roles/nzbget/defaults/main.yml
- roles/nzbget/tasks/main.yml
- roles/nzbhydra2/defaults/main.yml
- roles/nzbhydra2/tasks/main.yml
- roles/ombi/tasks/main.yml
- roles/radarr/defaults/main.yml
- roles/radarr/tasks/main.yml
- roles/sabnzbd/defaults/main.yml
- roles/sabnzbd/tasks/main.yml
- roles/sickbeard_mp4_automator/tasks/autoprocess_ini.yml
- roles/sonarr/defaults/main.yml
- roles/sonarr/tasks/main.yml
- roles/traktarr/tasks/main.yml
**`develop` branch**
Removed references to `/app` subdirectory
Removed hotio migrators from roles as the container's built in migrator will handle those gracefully without looping
> Update paths for hotio container changes, remove hotio migrators

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/config.yml
Emphasize the Discord for support
> Update GitHub Issue Templates

- roles/bazarr/tasks/subtasks/suitarr_migration.yml
- roles/jackett/tasks/subtasks/suitarr_migration.yml
- roles/lidarr/tasks/subtasks/suitarr_migration.yml
- roles/nzbget/tasks/subtasks/suitarr_migration.yml
- roles/nzbhydra2/tasks/subtasks/suitarr_migration.yml
- roles/radarr/tasks/subtasks/suitarr_migration.yml
- roles/sonarr/tasks/subtasks/suitarr_migration.yml
Remove migration from to `app` subfolder, fix migration from Suitarr subfolder structure
> Fix Suitarr Migrations
