roles/jackett/tasks/main.yml
roles/nzbget/tasks/main.yml
roles/nzbhydra/tasks/main.yml
roles/radarr/tasks/main.yml
roles/sonarr/tasks/main.yml

- Switched to using the Suitarr image for NZBGet (this will require the address alias to be `nzbget:8080` for Sonarr and Radarr) 
- Turned off backups for all Suitarr related containers.

NZBGet: now using the Suitarr image

---

roles/backup/tasks/main.yml

- During a scheduled backup, the cron scheduler task prevented the Pushover message task below it from running. This was fixed by simply moving the Pushover message task above it.

Backup task: Tweaked Pushover message to work during cron task

---

cloudbox.yml
roles/rclone/tasks/main.yml

Useful when wanting to update rclone to a newer version.  Tested OK.

Cloudbox: update-rclone tag

---

roles/backup/tasks/main.yml

It now records what containers were running before the backup so it can start them back up again. This covers users adding additional containers outside of CB.

updated backup role so it starts all previously running containers

---

roles/docker/tasks/main.yml

Now when you apt-get update, docker will not update.
Ref:
https://askubuntu.com/a/18656
http://docs.ansible.com/ansible/latest/apt_module.html

Docker: Prevent docker-ce from being upgraded

---

roles/unionfs/templates/unionfs.service.js2

- Gives extra time for other mounts to be loaded before Unionfs starts. 
- This helps with users who 1. have more than one mounts setup (eg rclone sftp mount for a feederbox) and 2. are using encrypted rclone mounts with plexdrive (takes longer to start up).

ServiceFiles: Added 30 sec start to unionfs

---

roles/plex/tasks/main.yml

- If Lazyman ip fails, then it will give those hosts a localhost ip.

Plex: tweaks to custom hosts

---

roles/common/tasks/main.yml

- used by Ansible's `ipv4` filter.

Common: Installs netaddr Python module

---

roles/common/tasks/main.yml

- Netaddr needs to be in both places, since Ansible will use either pip2 or pip3 depending on what he host is set to. 
- Removed pip install as that is already done via dependency commands. Installing it here can have the risk of python3 overwriting pip (vs just pip3).

Common: Fixed Pip issues

---

cloudbox.yml
roles/radarr4k/tasks/main.yml

- subdomain: `radarr4k`
- install: `--tags install-radarr4k`
- folder: `/opt/radarr4k/`
- Uses port `7879`.
- Only mounts `/mnt/`
- User's choice on where to keep 4K movies...
- Examples:
-  `/mnt/unionfs/Media/Movies/Movies4K/`
-  `/mnt/unionfs/Media/Movies4K/`
- Plex Autoscan will require tweaking, see "Configuring Plex Libraries" wiki page for more info.

New Role: radarr4k

---

roles/docker/files/daemon.json

This will control the log size. Requires a restart of the daemon and a re-run of the playbooks for it to take affect.

docker: Better log size management

---

roles/common/tasks/main.yml

When running a fresh installation on Debian Stretch, an unsupported distribution, the addition of Ubuntu specific repositories is not needed. Leaving these enabled causes a failed playbook run.
`cloudbox git:(master) sudo ansible-playbook cloudbox.yml -b --tags mediabox`
<snip>
`TASK [common : Add multiverse repositories] *************************************************************
Wednesday 19 December 2018  21:08:24 -0500 (0:00:02.102)       0:01:22.175 **** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The repository 'http://archive.ubuntu.com/ubuntu stretch Release' does not have a Release file.
failed: [localhost] (item=deb http://archive.ubuntu.com/ubuntu stretch multiverse) => {"changed": false, …

Common: Only add APT multiverse repo when running Ubuntu

---

roles/scripts/files/TorrentCleanup.py

Added a few lines to change so that this script works with sonarrv3. All that needed changing was something to handle the new test feature.
For future reference the script must be able to hand sonarr event type test properly ie exit with code 0 as I have done here.

CleanupTorrents.py fix for sonarrv3

---

roles/scripts/files/TorrentCleanup.py

Corrected the Sonarr V3 script test.
This allows Sonarr V3 to test the script correctly, without this the script will never run.
Sonarr V2 only tests for existance of file, it doesn't test anything within the script, hence why this is only required now with Sonarr V3.

TorrentCleanup: Sonarr V3 Test

---

.gitignore
Vagrantfile
vagrant.yml

This is a Vagrantfile for use and local development, some lines are added to .gitignore to facilitate the addition.
Vagrantfile should be usable with most local provisioners e.g. Parrallels, VBox and vmware_desktop.
It contains boxes for both Ubuntu 16.04 and Ubuntu 18.04. 
Cavecats: You might want to disable the ``` config.vm.provision "shell",``` Lines after first run to drasticly, improve speed and to avoid re-writing configs.

Vagrantfile for development

---

roles/watchtower/tasks/main.yml

This should close #298.
The quotes used, is not ansible standard, thus they are considered part of the string rather than, quotes.

use qoutes in watchtower role.

---

roles/settings/tasks/subtasks/migrator/accounts_yml/migration_01.yml
roles/settings/tasks/subtasks/migrator/accounts_yml/migration_02.yml
roles/settings/tasks/subtasks/migrator/backup_config_yml/migration_01.yml

If a username, email, or password in accounts.yml or backup_config.yml has 'null' in the middle of a word, it will be silently replaced and the user will end up wondering why their account does not authenticate.
This change makes the replace rule match and replace a line like `'property: null'` but not match `'property: nully-mcnullface'`.

Do not replace 'null' in the middle of a word

---

roles/settings/tasks/subtasks/migrator/accounts_yml/migration_01.yml
roles/settings/tasks/subtasks/migrator/accounts_yml/migration_02.yml

Prevents an error when a string starts with the text "null"
e.g. The domain nullsoft.com is truncated to soft.com

Ignore null when it's the start of a longer string

---

roles/tautulli/defaults/main.yml

Change Docker tag to nightly. With 2.2.0 Tautulli changed their Docker builds to use tags instead of just the ENV to specify the desired branch. Updating is now handled by updating the Docker image.
See: https://github.com/Tautulli/Tautulli/releases/tag/v2.2.0-beta

Tautulli: Change Docker tag

---

roles/settings/tasks/subtasks/migrator/accounts_yml/migration_01.yml
roles/settings/tasks/subtasks/migrator/accounts_yml/migration_02.yml
roles/settings/tasks/subtasks/migrator/adv_settings_yml/migration_01.yml
roles/settings/tasks/subtasks/migrator/adv_settings_yml/migration_02.yml
roles/settings/tasks/subtasks/migrator/backup_config_yml/migration_01.yml

Previous patch would fail on a null.tld domain or certain passwords with the string "null" at the start.
This makes the null regex more specific for only true null values. See https://regex101.com/r/YlxGLP/8 for details and test cases.

Made null replacmement more specific

---

roles/system/tasks/subtasks/cpufrequency.yml

Disable ondemand service to prevent govenor resetting back to powersave.

Disable ondemand service.

---

roles/nvidia/tasks/subtasks/driver.yml

Added the --dkms option to the runfile installer so the driver doesn't need to be reinstalled when upgrading the kernel.

Add dkms to Nvidia install.

---

roles/tautulli/defaults/main.yml

Change Tautulli to the stable release from the nightly one. The nightly release can break at any time and should not be used by anyone that isn't comfortable with that and able to diagnose issues with their installation.
Fixes #396.

Change Tautulli to the stable release

---

README.md

We get a lot of new users in the discord who don't seem to know that the wiki exists.  It gets a little lost in that block of badges and there's not a reference in the README other than that.

Add a more explicit reference to the wiki.

---

roles/radarr/defaults/main.yml

`unstable` tag deprecated in favor of `testing` tag.
This could also be changed to the `nightly` tag which would move to v3. I kept it as like-for-like for now.

Radarr: Update Docker image tag

---

roles/settings/tasks/subtasks/finish.yml

Can't ever be blank, and if this isn't a CI build they can't be the defaults [except user].

Verify user values in accounts.yml

---

roles/sonarr/defaults/main.yml

`phantom` tag deprecated in favor of `nightly` tag for Sonarr v3

Sonarr: Docker image tag update

---

roles/nzbget/defaults/main.yml

`unstable` tag deprecated in favor of `testing`

NZBGet: Update Docker image tag

---

roles/trackarr/templates/config.yaml.j2

Currently, ansible fails with:
```
TASK [trackarr : Pre-Install | Import default Trackarr config] 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'sonarr_name' is undefined"}
```

Updated Trackarr config to fix undefined variable error

---

defaults/adv_settings.yml.default
roles/organizr/tasks/main.yml

This should be a drop-in replacement coming from organizrtools/organizr-v2. It has worked in all our tests.
Key-changes:
- The nginx config file for the healthcheck is moved to it's own file, under /config/nginx/site-confs/healthcheck.
- Moving the install directory from /config/www/Dashboard to /config/www/organizr, Nginx should also be updated with this change.
- One tag. While we could have set PHP to use the unix socket as default, we opted to using a environment varible. We also moved the branch selector to be a environment variable.
Old | New
-- | --
organizrtools/organizr-v2 | organizr/organizr
organizrtools/organizr-v2:dev | -e branch=dev organizr/organizr
organizrtools/organizr-v2:php-fpm | -e fpm=true organizr/organizr
organizrtools/organizr-v2:dev-php-fpm | -e branch=dev -e …

Update Organizr Container + Variables

---

roles/system/tasks/subtasks/sysctl.yml

Update fs.inotify.max_user_watches from default 131072 to 524288
This modification should help with plex scans / rescans where plex errors out and the DB locks up.

Increase sysctl fs.inotify.max_user_watches

---

roles/plex_autoscan/templates/config.json.j2

Since plex-autoscan hasn't supported music for a long while, it makes sense to remove references to it from the base config.

Remove music references in PAS config
